/**
 * @file isqlsvr.h
 *
 * this file is generated by javah
 *
 * prototype of native methods of class isqlsvr
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class isqlsvr */

#ifndef _Included_isqlsvr
#define _Included_isqlsvr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     isqlsvr
 * Method:    sendRequest
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_isqlsvr_sendRequest
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
